macro(pj_read_versions path)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
  file(STRINGS "${path}" _pj_lines)
  foreach(_l IN LISTS _pj_lines)
    # CMake needs the real "\r" escape below; REGEX REPLACE "\\r" would not strip CRLF.
    string(REGEX REPLACE "\r$" "" _l "${_l}")
    if(_l MATCHES "^[ \t]*#" OR _l MATCHES "^[ \t]*$")
      continue()
    endif()
    if(_l MATCHES "^[ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*=[ \t]*(.*)$")
      string(STRIP "${CMAKE_MATCH_2}" _v)
      set(${CMAKE_MATCH_1} "${_v}")
    endif()
  endforeach()
endmacro()
